//go:build generate
// +build generate

// Remove existing CRDs
//go:generate rm -rf ../crds

// Generate deepcopy methodsets and CRD manifests
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../hack/boilerplate.go.txt paths=./... crd:crdVersions=v1 output:artifacts:config=../crds

// Sync the generated CRDs to every other place they have to exist.
//
// ../crds is the generated output, but it is not what reaches a cluster. The CRDs are VERSIONED AND
// SHIPPED by helm/oasgen-provider-crds (version: CHART_VERSION, substituted to the release tag), and
// they are the schema rest-dynamic-controller's envtest suite validates fixtures against. Both used to
// be hand-copied, and only ../crds was drift-checked, so the copy that users install could silently
// fall behind the generated one -- which is precisely what happened while fixing #51: `make generate`
// updated ../crds alone and the shipped chart kept the stale compareScope enum, with CI green. The
// testdata copy had drifted further still, generated by controller-gen v0.16.5 against a schema with
// no compareScope at all (#84).
//
// Generating into every destination, rather than listing them in a guard, means the guard cannot fall
// behind the set of destinations: a `git diff` after codegen covers whatever this writes.
//
// sh -c is required because go:generate does not run a shell, so the glob would not expand. Copying
// *.yaml rather than naming the file keeps this correct if this repo ever owns a second CRD; it adds
// and overwrites, never deletes, so the unrelated fixtures alongside the testdata copy are untouched.
//go:generate sh -c "cp ../crds/*.yaml ../../../helm/oasgen-provider-crds/templates/"
//go:generate sh -c "cp ../crds/*.yaml ../../rest-dynamic-controller/testdata/crds/"

package apis

import (
	_ "sigs.k8s.io/controller-tools/cmd/controller-gen" //nolint:typecheck
)
