//go:build !ignore_autogenerated

/*
Copyright 2025 Krateo SRL.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiRef) DeepCopyInto(out *ApiRef) {
	*out = *in
	if in.Extras != nil {
		in, out := &in.Extras, &out.Extras
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.NotFoundExpr != nil {
		in, out := &in.NotFoundExpr, &out.NotFoundExpr
		*out = new(JQProgram)
		**out = **in
	}
	if in.UpToDateExpr != nil {
		in, out := &in.UpToDateExpr, &out.UpToDateExpr
		*out = new(JQProgram)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiRef.
func (in *ApiRef) DeepCopy() *ApiRef {
	if in == nil {
		return nil
	}
	out := new(ApiRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsyncConfig) DeepCopyInto(out *AsyncConfig) {
	*out = *in
	in.OperationRef.DeepCopyInto(&out.OperationRef)
	in.Poll.DeepCopyInto(&out.Poll)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsyncConfig.
func (in *AsyncConfig) DeepCopy() *AsyncConfig {
	if in == nil {
		return nil
	}
	out := new(AsyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationField) DeepCopyInto(out *ConfigurationField) {
	*out = *in
	out.FromOpenAPI = in.FromOpenAPI
	in.FromRestDefinition.DeepCopyInto(&out.FromRestDefinition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationField.
func (in *ConfigurationField) DeepCopy() *ConfigurationField {
	if in == nil {
		return nil
	}
	out := new(ConfigurationField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuationTokenConfig) DeepCopyInto(out *ContinuationTokenConfig) {
	*out = *in
	out.Request = in.Request
	out.Response = in.Response
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuationTokenConfig.
func (in *ContinuationTokenConfig) DeepCopy() *ContinuationTokenConfig {
	if in == nil {
		return nil
	}
	out := new(ContinuationTokenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuationTokenRequest) DeepCopyInto(out *ContinuationTokenRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuationTokenRequest.
func (in *ContinuationTokenRequest) DeepCopy() *ContinuationTokenRequest {
	if in == nil {
		return nil
	}
	out := new(ContinuationTokenRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuationTokenResponse) DeepCopyInto(out *ContinuationTokenResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuationTokenResponse.
func (in *ContinuationTokenResponse) DeepCopy() *ContinuationTokenResponse {
	if in == nil {
		return nil
	}
	out := new(ContinuationTokenResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldMappingItem) DeepCopyInto(out *FieldMappingItem) {
	*out = *in
	if in.ValueMapping != nil {
		in, out := &in.ValueMapping, &out.ValueMapping
		*out = new(ValueMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.Resolver != nil {
		in, out := &in.Resolver, &out.Resolver
		*out = new(FieldResolver)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultIfAbsent != nil {
		in, out := &in.DefaultIfAbsent, &out.DefaultIfAbsent
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldMappingItem.
func (in *FieldMappingItem) DeepCopy() *FieldMappingItem {
	if in == nil {
		return nil
	}
	out := new(FieldMappingItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldResolver) DeepCopyInto(out *FieldResolver) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRefResolver)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldResolver.
func (in *FieldResolver) DeepCopy() *FieldResolver {
	if in == nil {
		return nil
	}
	out := new(FieldResolver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromOpenAPI) DeepCopyInto(out *FromOpenAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromOpenAPI.
func (in *FromOpenAPI) DeepCopy() *FromOpenAPI {
	if in == nil {
		return nil
	}
	out := new(FromOpenAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromRestDefinition) DeepCopyInto(out *FromRestDefinition) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromRestDefinition.
func (in *FromRestDefinition) DeepCopy() *FromRestDefinition {
	if in == nil {
		return nil
	}
	out := new(FromRestDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderItem) DeepCopyInto(out *HeaderItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderItem.
func (in *HeaderItem) DeepCopy() *HeaderItem {
	if in == nil {
		return nil
	}
	out := new(HeaderItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JQProgram) DeepCopyInto(out *JQProgram) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JQProgram.
func (in *JQProgram) DeepCopy() *JQProgram {
	if in == nil {
		return nil
	}
	out := new(JQProgram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KindApiVersion) DeepCopyInto(out *KindApiVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KindApiVersion.
func (in *KindApiVersion) DeepCopy() *KindApiVersion {
	if in == nil {
		return nil
	}
	out := new(KindApiVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationRef) DeepCopyInto(out *OperationRef) {
	*out = *in
	if in.JQ != nil {
		in, out := &in.JQ, &out.JQ
		*out = new(JQProgram)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationRef.
func (in *OperationRef) DeepCopy() *OperationRef {
	if in == nil {
		return nil
	}
	out := new(OperationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageNumberBodySignal) DeepCopyInto(out *PageNumberBodySignal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageNumberBodySignal.
func (in *PageNumberBodySignal) DeepCopy() *PageNumberBodySignal {
	if in == nil {
		return nil
	}
	out := new(PageNumberBodySignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageNumberConfig) DeepCopyInto(out *PageNumberConfig) {
	*out = *in
	out.Request = in.Request
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(PageNumberResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageNumberConfig.
func (in *PageNumberConfig) DeepCopy() *PageNumberConfig {
	if in == nil {
		return nil
	}
	out := new(PageNumberConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageNumberHeaderSignal) DeepCopyInto(out *PageNumberHeaderSignal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageNumberHeaderSignal.
func (in *PageNumberHeaderSignal) DeepCopy() *PageNumberHeaderSignal {
	if in == nil {
		return nil
	}
	out := new(PageNumberHeaderSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageNumberRequest) DeepCopyInto(out *PageNumberRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageNumberRequest.
func (in *PageNumberRequest) DeepCopy() *PageNumberRequest {
	if in == nil {
		return nil
	}
	out := new(PageNumberRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageNumberResponse) DeepCopyInto(out *PageNumberResponse) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(PageNumberHeaderSignal)
		**out = **in
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(PageNumberBodySignal)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageNumberResponse.
func (in *PageNumberResponse) DeepCopy() *PageNumberResponse {
	if in == nil {
		return nil
	}
	out := new(PageNumberResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pagination) DeepCopyInto(out *Pagination) {
	*out = *in
	if in.ContinuationToken != nil {
		in, out := &in.ContinuationToken, &out.ContinuationToken
		*out = new(ContinuationTokenConfig)
		**out = **in
	}
	if in.PageNumber != nil {
		in, out := &in.PageNumber, &out.PageNumber
		*out = new(PageNumberConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pagination.
func (in *Pagination) DeepCopy() *Pagination {
	if in == nil {
		return nil
	}
	out := new(Pagination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PollConfig) DeepCopyInto(out *PollConfig) {
	*out = *in
	if in.SuccessValues != nil {
		in, out := &in.SuccessValues, &out.SuccessValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailureValues != nil {
		in, out := &in.FailureValues, &out.FailureValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PollConfig.
func (in *PollConfig) DeepCopy() *PollConfig {
	if in == nil {
		return nil
	}
	out := new(PollConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryParam) DeepCopyInto(out *QueryParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryParam.
func (in *QueryParam) DeepCopy() *QueryParam {
	if in == nil {
		return nil
	}
	out := new(QueryParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestFieldMappingItem) DeepCopyInto(out *RequestFieldMappingItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestFieldMappingItem.
func (in *RequestFieldMappingItem) DeepCopy() *RequestFieldMappingItem {
	if in == nil {
		return nil
	}
	out := new(RequestFieldMappingItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	if in.VerbsDescription != nil {
		in, out := &in.VerbsDescription, &out.VerbsDescription
		*out = make([]VerbsDescription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Identifiers != nil {
		in, out := &in.Identifiers, &out.Identifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalStatusFields != nil {
		in, out := &in.AdditionalStatusFields, &out.AdditionalStatusFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigurationFields != nil {
		in, out := &in.ConfigurationFields, &out.ConfigurationFields
		*out = make([]ConfigurationField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludedSpecFields != nil {
		in, out := &in.ExcludedSpecFields, &out.ExcludedSpecFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObserveApiRef != nil {
		in, out := &in.ObserveApiRef, &out.ObserveApiRef
		*out = new(ApiRef)
		(*in).DeepCopyInto(*out)
	}
	if in.CreateApiRef != nil {
		in, out := &in.CreateApiRef, &out.CreateApiRef
		*out = new(ApiRef)
		(*in).DeepCopyInto(*out)
	}
	if in.DeleteApiRef != nil {
		in, out := &in.DeleteApiRef, &out.DeleteApiRef
		*out = new(ApiRef)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateApiRef != nil {
		in, out := &in.UpdateApiRef, &out.UpdateApiRef
		*out = new(ApiRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinition) DeepCopyInto(out *RestDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinition.
func (in *RestDefinition) DeepCopy() *RestDefinition {
	if in == nil {
		return nil
	}
	out := new(RestDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinitionList) DeepCopyInto(out *RestDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinitionList.
func (in *RestDefinitionList) DeepCopy() *RestDefinitionList {
	if in == nil {
		return nil
	}
	out := new(RestDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinitionSpec) DeepCopyInto(out *RestDefinitionSpec) {
	*out = *in
	in.Resource.DeepCopyInto(&out.Resource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinitionSpec.
func (in *RestDefinitionSpec) DeepCopy() *RestDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(RestDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDefinitionStatus) DeepCopyInto(out *RestDefinitionStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	out.Resource = in.Resource
	out.Configuration = in.Configuration
	if in.HasSecuritySchemes != nil {
		in, out := &in.HasSecuritySchemes, &out.HasSecuritySchemes
		*out = new(bool)
		**out = **in
	}
	if in.AuthSecretRBACNamespaces != nil {
		in, out := &in.AuthSecretRBACNamespaces, &out.AuthSecretRBACNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDefinitionStatus.
func (in *RestDefinitionStatus) DeepCopy() *RestDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(RestDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRefResolver) DeepCopyInto(out *SecretRefResolver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRefResolver.
func (in *SecretRefResolver) DeepCopy() *SecretRefResolver {
	if in == nil {
		return nil
	}
	out := new(SecretRefResolver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueAlias) DeepCopyInto(out *ValueAlias) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueAlias.
func (in *ValueAlias) DeepCopy() *ValueAlias {
	if in == nil {
		return nil
	}
	out := new(ValueAlias)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueMapping) DeepCopyInto(out *ValueMapping) {
	*out = *in
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]ValueAlias, len(*in))
		copy(*out, *in)
	}
	if in.JQ != nil {
		in, out := &in.JQ, &out.JQ
		*out = new(JQProgram)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueMapping.
func (in *ValueMapping) DeepCopy() *ValueMapping {
	if in == nil {
		return nil
	}
	out := new(ValueMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerbsDescription) DeepCopyInto(out *VerbsDescription) {
	*out = *in
	if in.RequestFieldMapping != nil {
		in, out := &in.RequestFieldMapping, &out.RequestFieldMapping
		*out = make([]RequestFieldMappingItem, len(*in))
		copy(*out, *in)
	}
	if in.FieldMapping != nil {
		in, out := &in.FieldMapping, &out.FieldMapping
		*out = make([]FieldMappingItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequestTransform != nil {
		in, out := &in.RequestTransform, &out.RequestTransform
		*out = new(JQProgram)
		**out = **in
	}
	if in.ResponseTransform != nil {
		in, out := &in.ResponseTransform, &out.ResponseTransform
		*out = new(JQProgram)
		**out = **in
	}
	if in.Pagination != nil {
		in, out := &in.Pagination, &out.Pagination
		*out = new(Pagination)
		(*in).DeepCopyInto(*out)
	}
	if in.SuccessCodes != nil {
		in, out := &in.SuccessCodes, &out.SuccessCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]HeaderItem, len(*in))
		copy(*out, *in)
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]QueryParam, len(*in))
		copy(*out, *in)
	}
	if in.TolerateCodes != nil {
		in, out := &in.TolerateCodes, &out.TolerateCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.NotFoundCodes != nil {
		in, out := &in.NotFoundCodes, &out.NotFoundCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.NotFoundBody != nil {
		in, out := &in.NotFoundBody, &out.NotFoundBody
		*out = new(JQProgram)
		**out = **in
	}
	if in.Async != nil {
		in, out := &in.Async, &out.Async
		*out = new(AsyncConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerbsDescription.
func (in *VerbsDescription) DeepCopy() *VerbsDescription {
	if in == nil {
		return nil
	}
	out := new(VerbsDescription)
	in.DeepCopyInto(out)
	return out
}
